class JobLetterRequest:
    def __init__(self, employee_name, purpose_of_request, addressee_name):
        self.employee_name = employee_name
        self.purpose_of_request = purpose_of_request
        self.addressee_name = addressee_name

    def generate_email(self):
        subject = f"Job Letter Request for {self.employee_name}"
        content = f"""
Dear HR Team,

I hope this message finds you well. I would like to request a Job Letter for {self.employee_name} for the purpose of {self.purpose_of_request}. Below are the details:

- Employee Name: {self.employee_name}
- Purpose of Request: {self.purpose_of_request}
- Addressee: {self.addressee_name}

Kindly generate the Job Letter and share it with me at your earliest convenience.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Best regards,
{self.employee_name}
"""
        return subject, content

# # Example usage:
# job_letter = JobLetterRequest(employee_name="John Doe", purpose_of_request="Visa application", addressee_name="Consulate General")
# print(job_letter.generate_email())


class SalaryCertificateRequest:
    def __init__(self, employee_name, purpose_of_request, addressee_name, language):
        self.employee_name = employee_name
        self.purpose_of_request = purpose_of_request
        self.addressee_name = addressee_name
        self.language = language

    def generate_email(self):
        subject = f"Salary Certificate Request for {self.employee_name} in {self.language}"
        content = f"""
Dear HR Team,

I would like to request a Salary Certificate for {self.employee_name}. Please generate the certificate in {self.language} for the purpose of {self.purpose_of_request}. The details are as follows:

- Employee Name: {self.employee_name}
- Purpose of Request: {self.purpose_of_request}
- Language: {self.language}
- Addressee: {self.addressee_name}

Please send the certificate at your earliest convenience.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Best regards,
{self.employee_name}
"""
        return subject, content

# # Example usage:
# salary_certificate = SalaryCertificateRequest(employee_name="Jane Doe", purpose_of_request="Loan application", addressee_name="Bank Manager", language="English")
# print(salary_certificate.generate_email())


class BankLetterRequest:
    def __init__(self, employee_name, purpose_of_request, addressee_name):
        self.employee_name = employee_name
        self.purpose_of_request = purpose_of_request
        self.addressee_name = addressee_name

    def generate_email(self):
        subject = f"Bank Letter Request for {self.employee_name}"
        content = f"""
Dear HR Team,

I am writing to request a Bank Letter for {self.employee_name} for the purpose of {self.purpose_of_request}. Below are the details required:

- Employee Name: {self.employee_name}
- Purpose of Request: {self.purpose_of_request}
- Addressee: {self.addressee_name}

Please prepare the letter and forward it to me when ready.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Best regards,
{self.employee_name}
"""
        return subject, content
# # Example usage:
# bank_letter = BankLetterRequest(employee_name="Alice Smith", purpose_of_request="Account opening", addressee_name="Bank Manager")
# print(bank_letter.generate_email())


class SalaryTransferLetterRequest:
    def __init__(self, employee_name, addressee_name):
        self.employee_name = employee_name
        self.addressee_name = addressee_name

    def generate_email(self):
        subject = f"Salary Transfer Letter Request for {self.employee_name}"
        content = f"""
Dear HR Team,

I am requesting a Salary Transfer Letter for {self.employee_name} for the purpose of transferring their salary to a different bank account. Kindly prepare the document with the details below:

- Employee Name: {self.employee_name}
- Addressee: {self.addressee_name}

Please share the letter as soon as it’s available.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Best regards,
{self.employee_name}
"""
        return subject, content
# # Example usage:
# salary_transfer_letter = SalaryTransferLetterRequest(employee_name="Bob Johnson", addressee_name="Bank Manager")
# print(salary_transfer_letter.generate_email())


class NOCRequest:
    def __init__(self, employee_name, purpose_of_request, addressee_name):
        self.employee_name = employee_name
        self.purpose_of_request = purpose_of_request
        self.addressee_name = addressee_name

    def generate_email(self):
        subject = f"No Objection Certificate (NOC) Request for {self.employee_name}"
        content = f"""
Dear HR Team,

I would like to request a No Objection Certificate (NOC) for {self.employee_name} for the purpose of {self.purpose_of_request}. The required details are:

- Employee Name: {self.employee_name}
- Purpose of Request: {self.purpose_of_request}
- Addressee: {self.addressee_name}

Kindly provide the NOC and send it to me at your earliest convenience.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Best regards,
{self.employee_name}
"""
        return subject, content
# # Example usage:
# noc_request = NOCRequest(employee_name="Charlie Brown", purpose_of_request="Travel", addressee_name="Embassy")
# print(noc_request.generate_email())


class GoldenVisaApplicationRequest:
    def __init__(self, employee_name):
        self.employee_name = employee_name

    def generate_email(self):
        subject = f"Golden Visa Application Letter Request for {self.employee_name}"
        content = f"""
Dear HR Team,

I am writing to request a Golden Visa Application Letter for {self.employee_name} in support of their Golden Visa application. Please generate the required letter and send it to me for further processing.

- Employee Name: {self.employee_name}

Please send the letter at your earliest opportunity.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Best regards,
{self.employee_name}
"""
        return subject, content
# # Example usage:
# golden_visa_application = GoldenVisaApplicationRequest(employee_name="David Lee")
# print(golden_visa_application.generate_email())
