import logging

from fastapi import Request, UploadFile, File
from fastapi import Depends, HTTPException, status

from fastapi import APIRouter
import json
from apps.web.routers.auths import auth
from utils.mail.mail import send_email_with_attachments
from utils.security import safe_log
from utils.mail.templates import(
    JobLetterRequest,
    SalaryCertificateRequest,
    BankLetterRequest,
    SalaryTransferLetterRequest,
    NOCRequest,
    GoldenVisaApplicationRequest,
)

from utils.utils import (
    get_current_user,
)

from apps.web.models.services import (
    LeaveResponse,
    LeaveForm,
    HrDocsResponse,
    HrDocsForm
)

from config import (
    CLIENT_ID,
    CLIENT_SECRET,
    TENANT,
    REDIRECT_URI,
    HR_EMAIL,
)

from apps.web.routers.auths import ACCESS_TOKEN, REFRESH_TOKEN
from apps.web.models.users import UserModel

from constants import ERROR_MESSAGES, WEBHOOK_MESSAGES
from utils.mail.fill_form import FillLeaveForm

router = APIRouter()


############################
# Leave Application
############################


@router.post("/leave", response_model=LeaveResponse)
async def submit_leave_form(
    request: Request,form_data: LeaveForm, session_user: UserModel = Depends(get_current_user)
):
    safe_log(logging.info, "Received leave application form", {"name": form_data.name, "from": form_data.leavefrom, "to": form_data.leaveto})
    if session_user:
        if not session_user.extra_sso:
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
        
        try:
            # Parse user SSO data
            extra_sso = json.loads(session_user.extra_sso)
            logging.debug(f"extra_sso: {extra_sso}")
            access_token = extra_sso.get(ACCESS_TOKEN)
            refresh_token = extra_sso.get(REFRESH_TOKEN)
            logging.debug(f"access_token: {access_token}")
            
            if not access_token:
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
                
            safe_log(logging.debug, "SSO token status", {
                "has_access_token": bool(access_token)
            })

            # Validate token using MSAL
            is_valid = auth.validate_token(access_token)
            if not is_valid:
                safe_log(logging.warning, "Token expired, attempting to refresh token")
                refresh_result = auth.refresh_token(refresh_token)
                if refresh_result and refresh_result.get("access_token"):
                    new_access_token = refresh_result.get("access_token")
                    safe_log(logging.info, "Token refresh successful, new token:", {"refresh_token": new_access_token})
                    if new_access_token:
                        is_valid = auth.validate_token(new_access_token)
                        safe_log(logging.info, "New token validation result:", {"is_valid": is_valid})
                        access_token = new_access_token
            if not is_valid:
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)

            
            subject = f"Leave of Absence Request - {form_data.name}"
            body = f"""
Dear HR,

I am writing to formally request a leave of absence from {form_data.leavefrom} to {form_data.leaveto}.

Thank you for considering my request. I look forward to your response.

Please see the attachment for details.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Sincerely,
{form_data.name}
"""
            recipient = HR_EMAIL
            if not recipient:
                safe_log(logging.warning, "HR_EMAIL not set, will use user's own email", {"email": session_user.email})
                recipient = session_user.email
            
            try:
                # fill the leave form
                TEMPPLATE_PATH = 'utils/mail/leave_template.pdf'
                OUTPUT_PATH = 'utils/mail/'

                data = {
                            '{NAME}': form_data.name,
                            '{ID}': form_data.employee_id,
                            '{JOBTITLE}': form_data.job_title,
                            '{DEPT}': form_data.dept,
                            '{LEAVETYPE}': form_data.type_of_leave,
                            '{REMARKS}': form_data.remarks,
                            '{LEAVEFROM}': form_data.leavefrom,
                            '{LEAVETO}': form_data.leaveto,
                            '{DAYS}': form_data.days,
                            '{ADDRESS}': form_data.address,
                            '{TELE}': form_data.tele,
                            '{EMAIL}': form_data.email,
                            '{DATE}': form_data.date,
                        }
                # get the form file path
                attachment_path = FillLeaveForm(TEMPPLATE_PATH, OUTPUT_PATH, data).fill_template()
                # make the mail content and send the mail can customize the subject and body
                attachment_name = 'Leave_Application_Form.pdf'

                safe_log(logging.info, "Preparing to send email", {"recipient": recipient, "subject": subject})
                
                try:
                    # Use new email sending function
                    success = await send_email_with_attachments(
                        access_token=access_token,
                        to_email=recipient,
                        subject=subject,
                        body=body,
                        attachment_paths=[attachment_path],  # Temporarily not sending attachments
                        cc_emails=[]  # CC to applicant
                    )
                except PermissionError as e:
                    safe_log(logging.error, "Permission error while sending email", exception=e)
                    raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.EMAIL_ERROR)
                except ValueError as e:
                    safe_log(logging.error, "Parameter error while sending email", exception=e)
                    raise HTTPException(status.HTTP_406_NOT_ACCEPTABLE, detail=ERROR_MESSAGES.ILIGAL_PARAM)
                except Exception as e:
                    safe_log(logging.error, "Unknown error occurred while sending email", exception=e)
                    raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Error sending email: {str(e)}")
                
                if not success:
                    raise Exception("Email sending failed")
                    
                safe_log(logging.info, "Email sent successfully", {"recipient": recipient})
            except Exception as e:
                safe_log(logging.error, "Error occurred while sending email", exception=e)
                raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Error sending email: {str(e)}")

            return {
                    "email": session_user.email,
                    "subject": subject,
                    "recipient": recipient,
                }
        except json.JSONDecodeError as e:
            safe_log(logging.error, "Unable to parse user SSO data", exception=e)
            raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="Invalid user SSO data")
    else:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=ERROR_MESSAGES.INVALID_CRED)


############################
# HR Documents Application
############################

@router.post("/hr-document", response_model=HrDocsResponse)
async def submit_hr_doc_form(
    request: Request,form_data: HrDocsForm, session_user = Depends(get_current_user)
):
    safe_log(logging.info, "Received HR document request form", {"name": form_data.name, "type": form_data.type_of_document})
    if session_user:
        if not session_user.extra_sso:
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
        
        try:
            # Parse user SSO data
            extra_sso = json.loads(session_user.extra_sso)
            access_token = extra_sso.get(ACCESS_TOKEN)
            refresh_token = extra_sso.get("refresh_token")
            
            if not access_token:
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
                
            safe_log(logging.info, "SSO token status", {
                "has_access_token": bool(access_token), 
                "has_refresh_token": bool(refresh_token)
            })

            if form_data.type_of_document == 1:
                # "Job Letter"
                subject, body = JobLetterRequest(form_data.name, form_data.purpose, form_data.addressee).generate_email()
            elif form_data.type_of_document == 2:
                # "Salary Certificate"
                subject, body = SalaryCertificateRequest(form_data.name, form_data.purpose, form_data.addressee, form_data.language).generate_email()
            elif form_data.type_of_document == 3:
                # "Bank letter"
                subject, body = BankLetterRequest(form_data.name, form_data.purpose, form_data.addressee).generate_email()
            elif form_data.type_of_document == 4:
                # "Salary Transfer letter"
                subject, body = SalaryTransferLetterRequest(form_data.name, form_data.addressee).generate_email()
            elif form_data.type_of_document == 5:
                # "NOC No Objection Certificate"
                subject, body = NOCRequest(form_data.name, form_data.purpose, form_data.addressee).generate_email()
            elif form_data.type_of_document == 6:
                # "Golden Visa Application letter"
                subject, body = GoldenVisaApplicationRequest(form_data.name).generate_email()
            else:
                raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, detail=ERROR_MESSAGES.INVALID_PARAM)

            recipient = HR_EMAIL
            if not recipient:
                safe_log(logging.warning, "HR_EMAIL not set, will use user's own email", {"email": session_user.email})
                recipient = session_user.email
            
            try:
                safe_log(logging.info, "Preparing to send email", {"recipient": recipient, "subject": subject})
                # Use new email sending function
                success = await send_email_with_attachments(
                    access_token=access_token,
                    to_email=recipient,
                    subject=subject,
                    body=body,
                    attachment_paths=[],  # Temporarily not sending attachments
                    cc_emails=[session_user.email]  # CC to applicant
                )
                if success:
                    safe_log(logging.info, "Email sent successfully", {"recipient": recipient})
            except PermissionError as e:
                safe_log(logging.error, "Permission error while sending email", exception=e)
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.EMAIL_ERROR)
            except ValueError as e:
                safe_log(logging.error, "Parameter error while sending email", exception=e)
                raise HTTPException(status.HTTP_406_NOT_ACCEPTABLE, detail=ERROR_MESSAGES.ILIGAL_PARAM)
            except Exception as e:
                safe_log(logging.error, "Unknown error occurred while sending email", exception=e)
                raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"Error sending email: {str(e)}")

            hr_docs_response = HrDocsResponse(
                email=session_user.email,
                subject=subject,
                recipient=recipient,
            )
            return hr_docs_response
        except json.JSONDecodeError as e:
            safe_log(logging.error, "Unable to parse user SSO data", exception=e)
            raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="Invalid user SSO data")
    else:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=ERROR_MESSAGES.INVALID_CRED)