import logging

from fastapi import Request, UploadFile, File
from fastapi import Depends, HTTPException, status
from fastapi_sso.sso.microsoft import MicrosoftSSO

from fastapi import APIRouter
import json
from utils.mail.mail import Mail
from utils.security import safe_log
from utils.mail.templates import(
    JobLetterRequest,
    SalaryCertificateRequest,
    BankLetterRequest,
    SalaryTransferLetterRequest,
    NOCRequest,
    GoldenVisaApplicationRequest,
)

from utils.utils import (
    get_current_user,
)

from apps.web.models.services import (
    LeaveResponse,
    LeaveForm,
    HrDocsResponse,
    HrDocsForm
)

from config import (
    CLIENT_ID,
    CLIENT_SECRET,
    TENANT,
    REDIRECT_URI,
    HR_EMAIL,
)

from apps.web.routers.auths import ACCESS_TOKEN

from constants import ERROR_MESSAGES, WEBHOOK_MESSAGES
router = APIRouter()


sso = MicrosoftSSO(
    client_id=CLIENT_ID,
    client_secret=CLIENT_SECRET,
    tenant=TENANT,
    redirect_uri=REDIRECT_URI,
    allow_insecure_http=True,
    scope=["User.Read", "Directory.Read.All", "User.ReadBasic.All", "Mail.Send"],
)


############################
# Leave Application
############################


@router.post("/leave", response_model=LeaveResponse)
async def submit_leave_form(
    request: Request,form_data: LeaveForm, session_user = Depends(get_current_user)
):
    safe_log(logging.info, "收到休假申请表单", {"name": form_data.name, "from": form_data.leavefrom, "to": form_data.leaveto})
    if session_user:
        if not session_user.extra_sso:
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
        
        try:
            # 解析用户SSO数据
            extra_sso = json.loads(session_user.extra_sso)
            access_token = extra_sso.get(ACCESS_TOKEN)
            refresh_token = extra_sso.get("refresh_token")
            
            if not access_token:
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
                
            safe_log(logging.info, "SSO令牌状态", {
                "has_access_token": bool(access_token), 
                "has_refresh_token": bool(refresh_token)
            })
            
            # 创建Mail对象，传递用户ID和刷新令牌
            mail = Mail(
                client_id=CLIENT_ID, 
                tenant_id=TENANT, 
                authorization=f"Bearer {access_token}",
                refresh_token=refresh_token,
                client_secret=CLIENT_SECRET,
                user_id=session_user.id
            )
            
            subject = f"Leave of Absence Request - {form_data.name}"
            body = f"""
Dear HR,

I am writing to formally request a leave of absence from {form_data.leavefrom} to {form_data.leaveto}.

Thank you for considering my request. I look forward to your response.

Please see the attachment for details.

Note: This email is automatically generated by the ServiceDesk Chatbot system.

Sincerely,
{form_data.name}
"""
            recipient = HR_EMAIL
            if not recipient:
                safe_log(logging.warning, "HR_EMAIL未设置，将使用用户自己的邮箱", {"email": session_user.email})
                recipient = session_user.email
            
            try:
                safe_log(logging.info, "准备发送邮件", {"recipient": recipient, "subject": subject})
                await mail.send_mail(subject, body, recipient, form_data)
                safe_log(logging.info, "邮件发送成功", {"recipient": recipient})
            except PermissionError as e:
                safe_log(logging.error, "发送邮件时权限错误", exception=e)
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.EMAIL_ERROR)
            except ValueError as e:
                safe_log(logging.error, "发送邮件时参数错误", exception=e)
                raise HTTPException(status.HTTP_406_NOT_ACCEPTABLE, detail=ERROR_MESSAGES.ILIGAL_PARAM)
            except Exception as e:
                safe_log(logging.error, "发送邮件时发生未知错误", exception=e)
                raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"发送邮件时出错: {str(e)}")

            return {
                    "email": session_user.email,
                    "subject": subject,
                    "recipient": recipient,
                }
        except json.JSONDecodeError as e:
            safe_log(logging.error, "无法解析用户SSO数据", exception=e)
            raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="无效的用户SSO数据")
    else:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=ERROR_MESSAGES.INVALID_CRED)


############################
# HR Documents Application
############################

@router.post("/hr-document", response_model=HrDocsResponse)
async def submit_hr_doc_form(
    request: Request,form_data: HrDocsForm, session_user = Depends(get_current_user)
):
    safe_log(logging.info, "收到HR文档请求表单", {"name": form_data.name, "type": form_data.type_of_document})
    if session_user:
        if not session_user.extra_sso:
            raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
        
        try:
            # 解析用户SSO数据
            extra_sso = json.loads(session_user.extra_sso)
            access_token = extra_sso.get(ACCESS_TOKEN)
            refresh_token = extra_sso.get("refresh_token")
            
            if not access_token:
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.INVALID_ACCOUNT)
                
            safe_log(logging.info, "SSO令牌状态", {
                "has_access_token": bool(access_token), 
                "has_refresh_token": bool(refresh_token)
            })
            
            # 创建Mail对象，传递用户ID和刷新令牌
            mail = Mail(
                client_id=CLIENT_ID, 
                tenant_id=TENANT, 
                authorization=f"Bearer {access_token}",
                refresh_token=refresh_token,
                client_secret=CLIENT_SECRET,
                user_id=session_user.id
            )

            if form_data.type_of_document == 1:
                # "Job Letter"
                subject, body = JobLetterRequest(form_data.name, form_data.purpose, form_data.addressee).generate_email()
            elif form_data.type_of_document == 2:
                # "Salary Certificate"
                subject, body = SalaryCertificateRequest(form_data.name, form_data.purpose, form_data.addressee, form_data.language).generate_email()
            elif form_data.type_of_document == 3:
                # "Bank letter"
                subject, body = BankLetterRequest(form_data.name, form_data.purpose, form_data.addressee).generate_email()
            elif form_data.type_of_document == 4:
                # "Salary Transfer letter"
                subject, body = SalaryTransferLetterRequest(form_data.name, form_data.addressee).generate_email()
            elif form_data.type_of_document == 5:
                # "NOC No Objection Certificate"
                subject, body = NOCRequest(form_data.name, form_data.purpose, form_data.addressee).generate_email()
            elif form_data.type_of_document == 6:
                # "Golden Visa Application letter"
                subject, body = GoldenVisaApplicationRequest(form_data.name).generate_email()
            else:
                raise HTTPException(status.HTTP_422_UNPROCESSABLE_ENTITY, detail=ERROR_MESSAGES.INVALID_PARAM)

            recipient = HR_EMAIL
            if not recipient:
                safe_log(logging.warning, "HR_EMAIL未设置，将使用用户自己的邮箱", {"email": session_user.email})
                recipient = session_user.email
            
            try:
                safe_log(logging.info, "准备发送邮件", {"recipient": recipient, "subject": subject})
                await mail.send_simple_mail(subject, body, recipient)
                safe_log(logging.info, "邮件发送成功", {"recipient": recipient})
            except PermissionError as e:
                safe_log(logging.error, "发送邮件时权限错误", exception=e)
                raise HTTPException(status.HTTP_401_UNAUTHORIZED, detail=ERROR_MESSAGES.EMAIL_ERROR)
            except ValueError as e:
                safe_log(logging.error, "发送邮件时参数错误", exception=e)
                raise HTTPException(status.HTTP_406_NOT_ACCEPTABLE, detail=ERROR_MESSAGES.ILIGAL_PARAM)
            except Exception as e:
                safe_log(logging.error, "发送邮件时发生未知错误", exception=e)
                raise HTTPException(status.HTTP_500_INTERNAL_SERVER_ERROR, detail=f"发送邮件时出错: {str(e)}")

            hr_docs_response = HrDocsResponse(
                email=session_user.email,
                subject=subject,
                recipient=recipient,
            )
            return hr_docs_response
        except json.JSONDecodeError as e:
            safe_log(logging.error, "无法解析用户SSO数据", exception=e)
            raise HTTPException(status.HTTP_400_BAD_REQUEST, detail="无效的用户SSO数据")
    else:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail=ERROR_MESSAGES.INVALID_CRED)